baseurl:

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default

keep_files: [thesaurus]

sass:
  style: expanded
  sass_dir: assets/css


collections:
  wat-hoe:
    output: true
  nieuws:
    output: true
  tools:
    output: true


excerpt_separator: <!--more-->